# Generated by Django 4.0.1 on 2022-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('License_num', models.CharField(max_length=20)),
                ('Vehicle_Number', models.CharField(max_length=10)),
                ('Vehicle_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('License_num', models.CharField(max_length=20)),
                ('Vehicle_Number', models.CharField(max_length=10)),
                ('Vehicle_Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('veh_no', models.CharField(max_length=50)),
            ],
        ),
    ]
