# Generated by Django 4.0.1 on 2022-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_licenseholder_phone_num_licenseholder_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseholder',
            name='Phone_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone_num',
            field=models.CharField(max_length=20),
        ),
    ]
