# Generated by Django 4.0.1 on 2022-03-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_licenseholder_phone_num_alter_user_phone_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_1',
        ),
    ]
