# Generated by Django 4.0.1 on 2022-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_remove_user_1_is_verified_user_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_1',
            name='License_num',
        ),
        migrations.RemoveField(
            model_name='user_1',
            name='Vehicle_Name',
        ),
        migrations.RemoveField(
            model_name='user_1',
            name='Vehicle_Number',
        ),
        migrations.AddField(
            model_name='user_extra',
            name='License_num',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_extra',
            name='Vehicle_Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_extra',
            name='Vehicle_Number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
