# Generated by Django 4.0.1 on 2022-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_remove_user_1_license_num_remove_user_1_vehicle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_extra',
            name='user',
        ),
        migrations.AddField(
            model_name='user_extra',
            name='First_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_extra',
            name='Last_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
