# Generated by Django 4.0.1 on 2022-04-13 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_remove_user_extra_user_user_extra_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_1',
        ),
        migrations.AddField(
            model_name='user_extra',
            name='License_img',
            field=models.ImageField(default='myProject\\tempo', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='licenseholder',
            name='validity',
            field=models.DateField(default=datetime.date(2022, 4, 13)),
        ),
    ]
